hpc <- read.csv("household_power_consumption.txt",sep=";")
hpc$Date <- as.Date(hpc$Date, "%d/%m/%Y")
hpc$Time <- strptime(paste(hpc$Date, hpc$Time), "%Y-%m-%d %H:%M:%S")
hpcGAP <- subset(hpc, Date=="2007-02-01" | Date=="2007-02-02")
png("plot3.png")
par(pch=".", col="black")
plot(hpcGAP$Time, as.numeric(as.character(hpcGAP$Sub_metering_1)), type="o", ylab="Energy Sub Metering", xlab="")
lines(hpcGAP$Time, as.numeric(as.character(hpcGAP$Sub_metering_2)), pch=".", type="o", col="red")
lines(hpcGAP$Time, as.numeric(as.character(hpcGAP$Sub_metering_3)), pch=".", type="o", col="blue")
legend('topright', legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, col=c("black", "red", "blue"))
dev.off()