hpc <- read.csv("household_power_consumption.txt",sep=";")
hpc$Date <- as.Date(hpc$Date, "%d/%m/%Y")
hpc$Time <- strptime(paste(hpc$Date, hpc$Time), "%Y-%m-%d %H:%M:%S")
hpcGAP <- subset(hpc, Date=="2007-02-01" | Date=="2007-02-02")
png("plot4.png")
par(mfrow=c(2,2))
par(pch=".", col="black")
plot(hpcGAP$Time, as.numeric(as.character(hpcGAP$Global_active_power)), type="o", ylab="Global Active Power", xlab="")
plot(hpcGAP$Time, as.numeric(as.character(hpcGAP$Voltage)), type="o", ylab="Voltage", xlab="")
plot(hpcGAP$Time, as.numeric(as.character(hpcGAP$Sub_metering_1)), type="o", ylab="Energy Sub Metering", xlab="")
lines(hpcGAP$Time, as.numeric(as.character(hpcGAP$Sub_metering_2)), pch=".", type="o", col="red")
lines(hpcGAP$Time, as.numeric(as.character(hpcGAP$Sub_metering_3)), pch=".", type="o", col="blue")
legend('topright', legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, col=c("black", "red", "blue"), bty="n")
par(pch=".", col="black")
plot(hpcGAP$Time, as.numeric(as.character(hpcGAP$Global_reactive_power)), type="o", ylab="Global Reactive Power", xlab="")
dev.off()